package zen.identity.auth;

import jakarta.annotation.security.PermitAll;
import jakarta.ws.rs.GET;
import jakarta.ws.rs.Path;
import jakarta.ws.rs.core.Response;

/**
 * Landing route for Supabase email links (confirmation, recovery). Supabase verifies the token on
 * its side and then redirects the browser here — the URL Supabase is given via {@code redirect_to}
 * (the {@code AUTH_REDIRECT_URI} the backend passes on signup/recover) — with the new session token
 * in the URL <em>fragment</em> ({@code #access_token=...}).
 *
 * <p>The fragment is client-side only and never reaches the server, so this endpoint cannot read
 * the token — which is precisely why the flow is shaped the way it is. This route's whole job is to
 * bounce the browser to the app <em>carrying the fragment along</em>; the app then reads it and
 * posts the tokens to {@code POST /api/v1/auth/session}, which validates them against Supabase and
 * issues the ordinary cookie session. Confirming an email therefore ends signed in, and a recovery
 * link ends on the set-a-new-password screen, without this endpoint ever seeing a token.
 *
 * <p>The redirect must not try to be cleverer than that. Anything that reads the token server-side
 * would need Supabase's PKCE flow, whose {@code code_verifier} is generated by whoever started the
 * sign-up — and in jZen that is the backend, on a different request from a different browser
 * session, so there is no verifier here to exchange with.
 *
 * <p>Lives in {@code zen-identity} as a framework resource (discovered from the Jandex-indexed jar
 * like {@code AuthResource}); it is outside the {@code api/} prefix, so the transport filter and
 * dual-mode negotiation do not apply.
 */
@Path("/auth/callback")
public class AuthCallbackResource {

  @GET
  @PermitAll
  public Response landing() {
    // 303 See Other to the app root. The browser carries the original fragment (the tokens) across
    // the redirect on its own, which is what lets the app consume them at the destination.
    //
    // The query flag is the fallback, not the mechanism: when a link arrives with no usable token
    // (an old link, a provider that stripped the fragment), the app has nothing to exchange and
    // falls back to greeting the user on the login screen. The Location is relative rather than a
    // Response.seeOther(URI), which JAX-RS would resolve against the request's host — wrong behind
    // the deployed URL; a relative path resolves against whatever origin served the link.
    return Response.status(Response.Status.SEE_OTHER)
        .header("Location", "/?auth=email-confirmed")
        .build();
  }
}
