"""Fixture tests for the Dart/Flutter dependency CVE gate. Run by `task test:scripts`.

Mirrors `test_audit_maven.py`'s shape and its reason for existing: every assertion here is a way
`audit-client.py` could report success without having checked anything, or could check the wrong
thing because `pubspec.lock` doesn't line up field-for-field with what a naive reader expects.

Nothing here reaches the network. `query_osv` is the only function that does, and the tests that
would need it exercise the parsing and the suppression rules on either side of it instead.

Written to the 3.9 floor, stdlib only (`unittest`, not pytest).
"""

from __future__ import annotations

import importlib.util
import sys
import tempfile
import textwrap
import unittest
from pathlib import Path

SCRIPTS = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(SCRIPTS))

_spec = importlib.util.spec_from_file_location("audit_client", SCRIPTS / "audit-client.py")
ac = importlib.util.module_from_spec(_spec)
sys.modules[_spec.name] = ac
_spec.loader.exec_module(ac)


class LockfileParsingTest(unittest.TestCase):
    def test_reads_a_hosted_package(self) -> None:
        lockfile = textwrap.dedent(
            """\
            # Generated by pub
            packages:
              http:
                dependency: "direct main"
                description:
                  name: http
                  sha256: "abc123"
                  url: "https://pub.dev"
                source: hosted
                version: "1.2.2"
            """
        )
        self.assertEqual({"http": {"1.2.2"}}, ac.parse_lockfile(lockfile))

    def test_sdk_entries_are_skipped(self) -> None:
        # `flutter`/`flutter_test` are pinned to the SDK, not to pub.dev, and have no version OSV's
        # Pub ecosystem can be asked about. Treating them as hosted would ask a meaningless query.
        lockfile = textwrap.dedent(
            """\
            packages:
              flutter:
                dependency: "direct main"
                description: flutter
                source: sdk
                version: "0.0.0"
              http:
                dependency: "direct main"
                description:
                  name: http
                  url: "https://pub.dev"
                source: hosted
                version: "1.2.2"
            """
        )
        self.assertEqual({"http": {"1.2.2"}}, ac.parse_lockfile(lockfile))

    def test_git_and_path_entries_are_skipped(self) -> None:
        lockfile = textwrap.dedent(
            """\
            packages:
              zen_core:
                dependency: "direct main"
                description:
                  path: "../zen_core"
                  relative: true
                source: path
                version: "0.1.0"
              app_links:
                dependency: "direct main"
                description:
                  name: app_links
                  url: "https://pub.dev"
                source: hosted
                version: "6.4.1"
            """
        )
        self.assertEqual({"app_links": {"6.4.1"}}, ac.parse_lockfile(lockfile))

    def test_the_same_package_pinned_by_two_workspaces_is_one_coordinate(self) -> None:
        # Two workspace lockfiles can pin the same transitive dependency to the same version.
        # Asking OSV about it twice is twice the traffic for one answer.
        lockfile = textwrap.dedent(
            """\
            packages:
              async:
                dependency: transitive
                description:
                  name: async
                  url: "https://pub.dev"
                source: hosted
                version: "2.13.1"
            """
        )
        first = ac.parse_lockfile(lockfile)
        second = ac.parse_lockfile(lockfile)
        merged: "dict[str, set[str]]" = {}
        for found in (first, second):
            for name, versions in found.items():
                merged.setdefault(name, set()).update(versions)
        self.assertEqual({"async": {"2.13.1"}}, merged)

    def test_a_field_out_of_order_or_missing_does_not_crash(self) -> None:
        # A hosted entry with no version line (a malformed or truncated lockfile) must be dropped
        # rather than reported with a version of None, which would crash the OSV query builder.
        lockfile = textwrap.dedent(
            """\
            packages:
              broken:
                dependency: transitive
                description:
                  name: broken
                  url: "https://pub.dev"
                source: hosted
            """
        )
        self.assertEqual({}, ac.parse_lockfile(lockfile))


class EmptyListIsAFailureTest(unittest.TestCase):
    def test_nothing_parsed_means_nothing_checked(self) -> None:
        with self.assertRaises(SystemExit) as raised:
            ac.lib.die("stand-in for the empty-lockfile path")
        self.assertNotEqual(0, raised.exception.code)

        self.assertEqual(
            {},
            ac.parse_lockfile("# Generated by pub\npackages:\n"),
            "a lockfile with no hosted packages must produce an empty dict, which main() turns"
            " into an exit",
        )


class SuppressionTest(unittest.TestCase):
    def setUp(self) -> None:
        self._tmp = tempfile.TemporaryDirectory()
        self.path = Path(self._tmp.name) / "audit-client-suppressions.txt"
        self._real = ac.SUPPRESSIONS_FILE
        ac.SUPPRESSIONS_FILE = self.path

    def tearDown(self) -> None:
        ac.SUPPRESSIONS_FILE = self._real
        self._tmp.cleanup()

    def test_an_entry_with_a_reason_is_accepted(self) -> None:
        self.path.write_text(
            "# a comment\n"
            "\n"
            "GHSA-aaaa-bbbb-cccc  web-only advisory; jZen never ships this package to web\n"
        )
        self.assertEqual(
            {"GHSA-aaaa-bbbb-cccc": "web-only advisory; jZen never ships this package to web"},
            ac.load_suppressions(),
        )

    def test_an_entry_without_a_reason_refuses_to_parse(self) -> None:
        self.path.write_text("GHSA-aaaa-bbbb-cccc\n")
        with self.assertRaises(SystemExit) as raised:
            ac.load_suppressions()
        self.assertNotEqual(0, raised.exception.code)

    def test_a_missing_file_is_no_suppressions_rather_than_an_error(self) -> None:
        self.assertEqual({}, ac.load_suppressions())

    def test_a_comment_only_file_suppresses_nothing(self) -> None:
        self.path.write_text("# everything here is prose\n#\n# GHSA-dddd-eeee-ffff  not active\n")
        self.assertEqual({}, ac.load_suppressions())


if __name__ == "__main__":
    unittest.main()
